import "./globals.css"
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Linkedin clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-warm-gray">{children}</body>
    </html>
  )
}
